-- ttymap.cities — curated list of globally-recognisable cities
-- with coordinates and country tags. Shared across plugins that
-- need a worldwide pool: geo_quiz picks targets at random; future
-- plugins can use it for tour planning, heatmaps, or seed data
-- without each one re-curating their own table.
--
-- ~150 entries spanning all inhabited continents, mixing megacities
-- (Tokyo, NYC, Paris) with regional capitals (Tallinn, La Paz,
-- Asunción) so a random pick produces real variety. Coordinates
-- are city-centric, accurate to ~0.1°. Country names use the
-- common short form (e.g. "USA" not "United States of America").
--
-- Loaded via `require "ttymap.cities"`. Returns an array of
--   { lon = number, lat = number, name = string, country = string }

return {
    -- ── Asia (~40) ───────────────────────────────────────────────
    { lon = 139.69, lat =  35.69, name = "Tokyo",         country = "Japan" },
    { lon = 135.50, lat =  34.69, name = "Osaka",         country = "Japan" },
    { lon = 135.77, lat =  35.01, name = "Kyoto",         country = "Japan" },
    { lon = 130.40, lat =  33.59, name = "Fukuoka",       country = "Japan" },
    { lon = 141.35, lat =  43.06, name = "Sapporo",       country = "Japan" },
    { lon = 116.40, lat =  39.90, name = "Beijing",       country = "China" },
    { lon = 121.47, lat =  31.23, name = "Shanghai",      country = "China" },
    { lon = 113.26, lat =  23.13, name = "Guangzhou",     country = "China" },
    { lon = 114.06, lat =  22.54, name = "Shenzhen",      country = "China" },
    { lon = 104.07, lat =  30.67, name = "Chengdu",       country = "China" },
    { lon = 108.95, lat =  34.27, name = "Xi'an",         country = "China" },
    { lon = 114.16, lat =  22.32, name = "Hong Kong",     country = "China" },
    { lon = 121.56, lat =  25.04, name = "Taipei",        country = "Taiwan" },
    { lon = 126.98, lat =  37.57, name = "Seoul",         country = "South Korea" },
    { lon = 129.03, lat =  35.18, name = "Busan",         country = "South Korea" },
    { lon = 125.75, lat =  39.04, name = "Pyongyang",     country = "North Korea" },
    { lon = 100.50, lat =  13.75, name = "Bangkok",       country = "Thailand" },
    { lon =  98.99, lat =  18.79, name = "Chiang Mai",    country = "Thailand" },
    { lon = 105.83, lat =  21.03, name = "Hanoi",         country = "Vietnam" },
    { lon = 106.66, lat =  10.82, name = "Ho Chi Minh",   country = "Vietnam" },
    { lon = 104.92, lat =  11.55, name = "Phnom Penh",    country = "Cambodia" },
    { lon = 102.61, lat =  17.97, name = "Vientiane",     country = "Laos" },
    { lon =  96.16, lat =  16.87, name = "Yangon",        country = "Myanmar" },
    { lon = 103.82, lat =   1.35, name = "Singapore",     country = "Singapore" },
    { lon = 101.69, lat =   3.14, name = "Kuala Lumpur",  country = "Malaysia" },
    { lon = 106.85, lat =  -6.21, name = "Jakarta",       country = "Indonesia" },
    { lon = 112.74, lat =  -7.25, name = "Surabaya",      country = "Indonesia" },
    { lon = 115.18, lat =  -8.41, name = "Denpasar",      country = "Indonesia" },
    { lon = 120.98, lat =  14.60, name = "Manila",        country = "Philippines" },
    { lon =  72.83, lat =  19.08, name = "Mumbai",        country = "India" },
    { lon =  77.10, lat =  28.70, name = "Delhi",         country = "India" },
    { lon =  77.59, lat =  12.97, name = "Bengaluru",     country = "India" },
    { lon =  88.36, lat =  22.57, name = "Kolkata",       country = "India" },
    { lon =  80.27, lat =  13.08, name = "Chennai",       country = "India" },
    { lon =  78.49, lat =  17.39, name = "Hyderabad",     country = "India" },
    { lon =  79.85, lat =   6.93, name = "Colombo",       country = "Sri Lanka" },
    { lon =  90.41, lat =  23.81, name = "Dhaka",         country = "Bangladesh" },
    { lon =  85.32, lat =  27.72, name = "Kathmandu",     country = "Nepal" },
    { lon =  67.01, lat =  24.86, name = "Karachi",       country = "Pakistan" },
    { lon =  74.36, lat =  31.55, name = "Lahore",        country = "Pakistan" },
    { lon = 106.92, lat =  47.92, name = "Ulaanbaatar",   country = "Mongolia" },
    { lon =  69.24, lat =  41.31, name = "Tashkent",      country = "Uzbekistan" },
    { lon =  76.93, lat =  43.24, name = "Almaty",        country = "Kazakhstan" },
    -- ── Middle East (~12) ────────────────────────────────────────
    { lon =  51.39, lat =  35.69, name = "Tehran",        country = "Iran" },
    { lon =  44.36, lat =  33.32, name = "Baghdad",       country = "Iraq" },
    { lon =  46.68, lat =  24.71, name = "Riyadh",        country = "Saudi Arabia" },
    { lon =  39.81, lat =  21.42, name = "Mecca",         country = "Saudi Arabia" },
    { lon =  55.27, lat =  25.20, name = "Dubai",         country = "UAE" },
    { lon =  54.37, lat =  24.45, name = "Abu Dhabi",     country = "UAE" },
    { lon =  51.53, lat =  25.29, name = "Doha",          country = "Qatar" },
    { lon =  47.97, lat =  29.38, name = "Kuwait City",   country = "Kuwait" },
    { lon =  35.21, lat =  31.77, name = "Jerusalem",     country = "Israel" },
    { lon =  34.78, lat =  32.08, name = "Tel Aviv",      country = "Israel" },
    { lon =  35.93, lat =  31.95, name = "Amman",         country = "Jordan" },
    { lon =  35.51, lat =  33.89, name = "Beirut",        country = "Lebanon" },
    -- ── Europe (~40) ─────────────────────────────────────────────
    { lon =  -0.13, lat =  51.51, name = "London",        country = "United Kingdom" },
    { lon =  -3.20, lat =  55.95, name = "Edinburgh",     country = "United Kingdom" },
    { lon =  -2.24, lat =  53.48, name = "Manchester",    country = "United Kingdom" },
    { lon =  -6.27, lat =  53.35, name = "Dublin",        country = "Ireland" },
    { lon =   2.35, lat =  48.86, name = "Paris",         country = "France" },
    { lon =   5.37, lat =  43.30, name = "Marseille",     country = "France" },
    { lon =   7.27, lat =  43.71, name = "Nice",          country = "France" },
    { lon =   4.83, lat =  45.76, name = "Lyon",          country = "France" },
    { lon =  13.41, lat =  52.52, name = "Berlin",        country = "Germany" },
    { lon =  11.58, lat =  48.14, name = "Munich",        country = "Germany" },
    { lon =  10.00, lat =  53.55, name = "Hamburg",       country = "Germany" },
    { lon =   8.68, lat =  50.11, name = "Frankfurt",     country = "Germany" },
    { lon =   4.90, lat =  52.37, name = "Amsterdam",     country = "Netherlands" },
    { lon =   4.35, lat =  50.85, name = "Brussels",      country = "Belgium" },
    { lon =  12.50, lat =  41.90, name = "Rome",          country = "Italy" },
    { lon =   9.19, lat =  45.46, name = "Milan",         country = "Italy" },
    { lon =  14.27, lat =  40.85, name = "Naples",        country = "Italy" },
    { lon =  12.34, lat =  45.44, name = "Venice",        country = "Italy" },
    { lon =  11.25, lat =  43.77, name = "Florence",      country = "Italy" },
    { lon =  -3.70, lat =  40.42, name = "Madrid",        country = "Spain" },
    { lon =   2.17, lat =  41.39, name = "Barcelona",     country = "Spain" },
    { lon =  -5.99, lat =  37.39, name = "Seville",       country = "Spain" },
    { lon =  -9.14, lat =  38.72, name = "Lisbon",        country = "Portugal" },
    { lon =  -8.62, lat =  41.15, name = "Porto",         country = "Portugal" },
    { lon =  23.73, lat =  37.98, name = "Athens",        country = "Greece" },
    { lon =  16.37, lat =  48.21, name = "Vienna",        country = "Austria" },
    { lon =   8.55, lat =  47.37, name = "Zurich",        country = "Switzerland" },
    { lon =   6.14, lat =  46.20, name = "Geneva",        country = "Switzerland" },
    { lon =  14.42, lat =  50.07, name = "Prague",        country = "Czechia" },
    { lon =  21.01, lat =  52.23, name = "Warsaw",        country = "Poland" },
    { lon =  19.04, lat =  47.50, name = "Budapest",      country = "Hungary" },
    { lon =  26.10, lat =  44.43, name = "Bucharest",     country = "Romania" },
    { lon =  23.32, lat =  42.70, name = "Sofia",         country = "Bulgaria" },
    { lon =  20.46, lat =  44.79, name = "Belgrade",      country = "Serbia" },
    { lon =  15.97, lat =  45.81, name = "Zagreb",        country = "Croatia" },
    { lon =  18.07, lat =  59.33, name = "Stockholm",     country = "Sweden" },
    { lon =  10.75, lat =  59.91, name = "Oslo",          country = "Norway" },
    { lon =  12.57, lat =  55.68, name = "Copenhagen",    country = "Denmark" },
    { lon =  24.94, lat =  60.17, name = "Helsinki",      country = "Finland" },
    { lon =  24.76, lat =  59.44, name = "Tallinn",       country = "Estonia" },
    { lon =  24.11, lat =  56.95, name = "Riga",          country = "Latvia" },
    { lon =  25.28, lat =  54.69, name = "Vilnius",       country = "Lithuania" },
    { lon = -21.94, lat =  64.15, name = "Reykjavik",     country = "Iceland" },
    { lon =  37.62, lat =  55.75, name = "Moscow",        country = "Russia" },
    { lon =  30.31, lat =  59.94, name = "St. Petersburg",country = "Russia" },
    { lon =  82.93, lat =  55.04, name = "Novosibirsk",   country = "Russia" },
    { lon = 131.87, lat =  43.12, name = "Vladivostok",   country = "Russia" },
    { lon =  30.52, lat =  50.45, name = "Kyiv",          country = "Ukraine" },
    { lon =  27.57, lat =  53.90, name = "Minsk",         country = "Belarus" },
    { lon =  28.98, lat =  41.01, name = "Istanbul",      country = "Turkey" },
    { lon =  32.85, lat =  39.93, name = "Ankara",        country = "Turkey" },
    -- ── Africa (~22) ─────────────────────────────────────────────
    { lon =  31.24, lat =  30.04, name = "Cairo",         country = "Egypt" },
    { lon =  29.92, lat =  31.20, name = "Alexandria",    country = "Egypt" },
    { lon =   3.06, lat =  36.75, name = "Algiers",       country = "Algeria" },
    { lon =  10.18, lat =  36.81, name = "Tunis",         country = "Tunisia" },
    { lon =  -7.59, lat =  33.57, name = "Casablanca",    country = "Morocco" },
    { lon =  -7.99, lat =  31.63, name = "Marrakech",     country = "Morocco" },
    { lon = -17.45, lat =  14.69, name = "Dakar",         country = "Senegal" },
    { lon =   3.38, lat =   6.46, name = "Lagos",         country = "Nigeria" },
    { lon =   7.49, lat =   9.07, name = "Abuja",         country = "Nigeria" },
    { lon =  -0.19, lat =   5.60, name = "Accra",         country = "Ghana" },
    { lon =  -4.00, lat =   5.36, name = "Abidjan",       country = "Ivory Coast" },
    { lon =  15.31, lat =  -4.32, name = "Kinshasa",      country = "DR Congo" },
    { lon =  13.23, lat =  -8.84, name = "Luanda",        country = "Angola" },
    { lon =  36.82, lat =  -1.29, name = "Nairobi",       country = "Kenya" },
    { lon =  32.58, lat =   0.35, name = "Kampala",       country = "Uganda" },
    { lon =  38.74, lat =   9.03, name = "Addis Ababa",   country = "Ethiopia" },
    { lon =  32.55, lat =  15.50, name = "Khartoum",      country = "Sudan" },
    { lon =  39.20, lat =  -6.79, name = "Dar es Salaam", country = "Tanzania" },
    { lon =  18.42, lat = -33.92, name = "Cape Town",     country = "South Africa" },
    { lon =  28.04, lat = -26.20, name = "Johannesburg",  country = "South Africa" },
    { lon =  31.05, lat = -17.83, name = "Harare",        country = "Zimbabwe" },
    { lon =  47.52, lat = -18.91, name = "Antananarivo",  country = "Madagascar" },
    -- ── North America (~22) ──────────────────────────────────────
    { lon = -74.01, lat =  40.71, name = "New York",      country = "USA" },
    { lon =-118.24, lat =  34.05, name = "Los Angeles",   country = "USA" },
    { lon = -87.65, lat =  41.88, name = "Chicago",       country = "USA" },
    { lon = -95.37, lat =  29.76, name = "Houston",       country = "USA" },
    { lon = -96.80, lat =  32.78, name = "Dallas",        country = "USA" },
    { lon =-122.42, lat =  37.77, name = "San Francisco", country = "USA" },
    { lon =-122.33, lat =  47.61, name = "Seattle",       country = "USA" },
    { lon = -71.06, lat =  42.36, name = "Boston",        country = "USA" },
    { lon = -77.04, lat =  38.91, name = "Washington DC", country = "USA" },
    { lon = -80.19, lat =  25.76, name = "Miami",         country = "USA" },
    { lon = -84.39, lat =  33.75, name = "Atlanta",       country = "USA" },
    { lon = -90.07, lat =  29.95, name = "New Orleans",   country = "USA" },
    { lon =-104.99, lat =  39.74, name = "Denver",        country = "USA" },
    { lon =-115.14, lat =  36.17, name = "Las Vegas",     country = "USA" },
    { lon =-149.90, lat =  61.22, name = "Anchorage",     country = "USA" },
    { lon =-157.86, lat =  21.31, name = "Honolulu",      country = "USA" },
    { lon = -79.38, lat =  43.65, name = "Toronto",       country = "Canada" },
    { lon = -73.57, lat =  45.50, name = "Montreal",      country = "Canada" },
    { lon =-123.12, lat =  49.28, name = "Vancouver",     country = "Canada" },
    { lon = -75.70, lat =  45.42, name = "Ottawa",        country = "Canada" },
    { lon =-114.07, lat =  51.05, name = "Calgary",       country = "Canada" },
    { lon = -99.13, lat =  19.43, name = "Mexico City",   country = "Mexico" },
    -- ── Central America & Caribbean (~7) ─────────────────────────
    { lon =-103.35, lat =  20.66, name = "Guadalajara",   country = "Mexico" },
    { lon = -86.87, lat =  21.16, name = "Cancun",        country = "Mexico" },
    { lon = -82.36, lat =  23.13, name = "Havana",        country = "Cuba" },
    { lon = -79.51, lat =   8.98, name = "Panama City",   country = "Panama" },
    { lon = -90.51, lat =  14.63, name = "Guatemala City",country = "Guatemala" },
    { lon = -84.09, lat =   9.93, name = "San José",      country = "Costa Rica" },
    { lon = -66.11, lat =  18.47, name = "San Juan",      country = "Puerto Rico" },
    -- ── South America (~12) ──────────────────────────────────────
    { lon = -77.04, lat = -12.05, name = "Lima",          country = "Peru" },
    { lon = -68.15, lat = -16.50, name = "La Paz",        country = "Bolivia" },
    { lon = -70.65, lat = -33.45, name = "Santiago",      country = "Chile" },
    { lon = -58.38, lat = -34.61, name = "Buenos Aires",  country = "Argentina" },
    { lon = -56.19, lat = -34.90, name = "Montevideo",    country = "Uruguay" },
    { lon = -57.64, lat = -25.30, name = "Asunción",      country = "Paraguay" },
    { lon = -43.20, lat = -22.91, name = "Rio de Janeiro",country = "Brazil" },
    { lon = -46.63, lat = -23.55, name = "São Paulo",     country = "Brazil" },
    { lon = -47.93, lat = -15.78, name = "Brasília",      country = "Brazil" },
    { lon = -38.51, lat = -12.97, name = "Salvador",      country = "Brazil" },
    { lon = -74.07, lat =   4.71, name = "Bogotá",        country = "Colombia" },
    { lon = -78.51, lat =  -0.18, name = "Quito",         country = "Ecuador" },
    { lon = -66.92, lat =  10.49, name = "Caracas",       country = "Venezuela" },
    -- ── Oceania (~6) ─────────────────────────────────────────────
    { lon = 151.21, lat = -33.87, name = "Sydney",        country = "Australia" },
    { lon = 144.96, lat = -37.81, name = "Melbourne",     country = "Australia" },
    { lon = 153.03, lat = -27.47, name = "Brisbane",      country = "Australia" },
    { lon = 115.86, lat = -31.95, name = "Perth",         country = "Australia" },
    { lon = 174.76, lat = -36.85, name = "Auckland",      country = "New Zealand" },
    { lon = 174.78, lat = -41.29, name = "Wellington",    country = "New Zealand" },
}
